# Generated by Django 4.2.1 on 2023-05-17 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("cargo", models.CharField(blank=True, max_length=255, null=True)),
                ("categoria", models.CharField(max_length=255)),
                ("formacao", models.CharField(max_length=255)),
                ("numero_de_agente", models.IntegerField()),
                ("nif", models.CharField(max_length=255)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars"),
                ),
                ("data_de_entrada", models.DateField()),
                ("activo", models.BooleanField(default=True)),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funcionarios",
                        to="employee.departamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Licenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("medica", "Licença médica"),
                            ("ferias", "Férias"),
                            ("maternidade", "Licença maternidade"),
                            ("paternidae", "Licença paternidade"),
                        ],
                        default="medica",
                        max_length=20,
                    ),
                ),
                ("inicio", models.DateField()),
                ("fim", models.DateField()),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licencas",
                        to="employee.funcionario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoFuncionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("arquivo", models.FileField(upload_to="documentos/funcionarios")),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_funcionario",
                        to="employee.funcionario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("nota", models.FloatField()),
                ("comentario", models.TextField(blank=True, null=True)),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="employee.funcionario",
                    ),
                ),
            ],
        ),
    ]
